apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: example-e2ebuildserver.example.com.20240125213808.0.0
spec:
  refName: example-e2ebuildserver.example.com
  version: 20240125213808.0.0
  releaseNotes: |
    Release v20240125213808.0.0 of package example-e2ebuildserver.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ci/development/tests/e2e-build-server/example-e2ebuildserver-bundle@sha256:13171670b8e0daea77d4e8295ad2a433fbb17f706e05e236ad584b87c3fc5d2a
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
