apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: example-e2ebuildserver.example.com.20240125013347.0.0
spec:
  refName: example-e2ebuildserver.example.com
  version: 20240125013347.0.0
  releaseNotes: |
    Release v20240125013347.0.0 of package example-e2ebuildserver.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ci/development/tests/e2e-build-server/example-e2ebuildserver-bundle@sha256:47f5f953b097b3e5822460e7fc776d1eeaa01865d408904d3d2a1c45a9d9a393
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
